export enum TFGrid {
  NoneValue = 73,
  StorageOverflow,

  CannotCreateNode,
  NodeNotExists,
  NodeWithTwinIdExists,
  CannotDeleteNode,
  NodeDeleteNotAuthorized,
  NodeUpdateNotAuthorized,

  FarmExists,
  FarmNotExists,
  CannotCreateFarmWrongTwin,
  CannotUpdateFarmWrongTwin,
  CannotDeleteFarm,
  CannotDeleteFarmWithPublicIPs,
  CannotDeleteFarmWithNodesAssigned,
  CannotDeleteFarmWrongTwin,
  IpExists,
  IpNotExists,

  EntityWithNameExists,
  EntityWithPubkeyExists,
  EntityNotExists,
  EntitySignatureDoesNotMatch,
  EntityWithSignatureAlreadyExists,
  CannotUpdateEntity,
  CannotDeleteEntity,
  SignatureLengthIsIncorrect,

  TwinExists,
  TwinNotExists,
  TwinWithPubkeyExists,
  CannotCreateTwin,
  UnauthorizedToUpdateTwin,
  TwinCannotBoundToItself,

  PricingPolicyExists,
  PricingPolicyNotExists,
  PricingPolicyWithDifferentIdExists,
  CertificationCodeExists,
  FarmingPolicyAlreadyExists,
  FarmPayoutAdressAlreadyRegistered,
  FarmerDoesNotHaveEnoughFunds,
  UserDidNotSignTermsAndConditions,
  FarmerDidNotSignTermsAndConditions,
  FarmerNotAuthorized,
  InvalidFarmName,

  AlreadyCertifier,
  NotCertifier,
  NotAllowedToCertifyNode,

  FarmingPolicyNotExists,

  RelayTooShort,
  RelayTooLong,
  InvalidRelay,

  FarmNameTooShort,
  FarmNameTooLong,
  InvalidPublicIP,
  PublicIPTooShort,
  PublicIPTooLong,
  GatewayIPTooShort,
  GatewayIPTooLong,

  IP4TooShort,
  IP4TooLong,
  InvalidIP4,
  GW4TooShort,
  GW4TooLong,
  InvalidGW4,
  IP6TooShort,
  IP6TooLong,
  InvalidIP6,
  GW6TooShort,
  GW6TooLong,
  InvalidGW6,
  DomainTooShort,
  DomainTooLong,
  InvalidDomain,
  MethodIsDeprecated,
  InterfaceNameTooShort,
  InterfaceNameTooLong,
  InvalidInterfaceName,
  InterfaceMacTooShort,
  InterfaceMacTooLong,
  InvalidMacAddress,
  InterfaceIpTooShort,
  InterfaceIpTooLong,
  InvalidInterfaceIP,
  InvalidZosVersion,
  FarmingPolicyExpired,

  InvalidHRUInput,
  InvalidSRUInput,
  InvalidCRUInput,
  InvalidMRUInput,

  LatitudeInputTooShort,
  LatitudeInputTooLong,
  InvalidLatitudeInput,
  LongitudeInputTooShort,
  LongitudeInputTooLong,
  InvalidLongitudeInput,
  CountryNameTooShort,
  CountryNameTooLong,
  InvalidCountryName,
  CityNameTooShort,
  CityNameTooLong,
  InvalidCityName,
  InvalidCountryCityPair,

  SerialNumberTooShort,
  SerialNumberTooLong,
  InvalidSerialNumber,

  DocumentLinkInputTooShort,
  DocumentLinkInputTooLong,
  InvalidDocumentLinkInput,
  DocumentHashInputTooShort,
  DocumentHashInputTooLong,
  InvalidDocumentHashInput,

  InvalidPublicConfig,
  UnauthorizedToChangePowerTarget,
  InvalidRelayAddress,
  InvalidTimestampHint,
}
