export enum tftBridge {
  ValidatorExists = 187,
  ValidatorNotExists,
  TransactionValidatorExists,
  TransactionValidatorNotExists,
  MintTransactionExists,
  MintTransactionAlreadyExecuted,
  MintTransactionNotExists,
  BurnTransactionExists,
  BurnTransactionNotExists,
  BurnSignatureExists,
  EnoughBurnSignaturesPresent,
  RefundSignatureExists,
  BurnTransactionAlreadyExecuted,
  RefundTransactionNotExists,
  RefundTransactionAlreadyExecuted,
  EnoughRefundSignaturesPresent,
  NotEnoughBalanceToSwap,
  AmountIsLessThanWithdrawFee,
  AmountIsLessThanDepositFee,
  WrongParametersProvided,
  InvalidStellarPublicKey,
}
