name: Playground Selenium Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select which Git branch to run against"
        required: true
        default: "development"
      network:
        description: "Select the target environment"
        required: true
        type: choice
        default: "dev"
        options:
          - local
          - dev
          - qa
          - test
          - main
  schedule:
    - cron: "0 6 * * *"

jobs:
  selenium-run:
    runs-on: ubuntu-latest
    env:
      NETWORK: ${{ github.event.inputs.network }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install -r packages/playground/tests/frontend_selenium/requirements.txt
          pip install pytest-html

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install JS dependencies & build
        if: ${{ github.event.inputs.network == 'local' }}
        run: |
          yarn install
          yarn lerna run build

      - name: Start playground server
        run: make run project=playground &

      - name: Wait for server to be ready
        run: sleep 60

      - name: Run Selenium tests
        working-directory: ./packages/playground/tests/frontend_selenium
        env:
          TFCHAIN_MNEMONICS: ${{ secrets.TFCHAIN_MNEMONICS }}
          TFCHAIN_NODE_MNEMONICS: ${{ secrets.TFCHAIN_NODE_MNEMONICS }}
          STELLAR_ADDRESS: ${{ secrets.STELLAR_ADDRESS }}
          EMAIL: ${{ secrets.EMAIL }}
          NETWORK: ${{ env.NETWORK }}
        run: |
          python -m pytest -v --html=report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-report-${{ env.NETWORK }}
          path: packages/playground/tests/frontend_selenium/report.html
